---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodalingresser
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: nodalingresser
  template:
    metadata:
      labels:
        app: nodalingresser
    spec:
      serviceAccountName: nodalingresser
      containers:
        - name: nodalingresser
          image: koobz/nodalingresser
          command:
            - /nodalingresser
          args:
            - --debug
            - --google-dns-service-account
            - /secrets/nodalingresser.json
            - --google-dns-project
            - api-project-12345
            - --google-dns-zone
            - k8s-example-com
            - --google-dns-record
            - "*.k8s.example.com."
          volumeMounts:
            - name: secrets
              mountPath: "/secrets"
      volumes:
        - name: secrets
          secret:
            # Generate the service account json with sa.sh then...
            # kubetl -n kube-system create secret generic nodalingresser --from-file nodalingresser.json
            secretName: nodalingresser
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodalingresser-node-reader
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nodalingresser-read-nodes
subjects:
  - kind: ServiceAccount
    name: nodalingresser
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: nodalingresser-node-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodalingresser
  namespace: kube-system
